/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package repository;

import domain.RmRawRule;
import org.springframework.transaction.annotation.Transactional;
import repository.support.GenericRepository;

import javax.inject.Named;
import javax.inject.Singleton;
import java.util.UUID;

@Named
@Singleton
public class RawRuleRepository extends GenericRepository<RmRawRule, UUID> {

    public RawRuleRepository() {
        super(RmRawRule.class);
    }

    @Override
    public RmRawRule getNew() {
        return null;
    }
}